<a href="https://colab.research.google.com/github/AleksejSip/laba/blob/main/tgb3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Бблиотека

In [19]:
import numpy as np

from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

ДАнные

In [20]:
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

29515/29515 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
26421880/26421880 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
5148/5148 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
4422102/4422102 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


Преобразование

In [21]:
x_train = x_train.reshape(x_train.shape[0], -1) / 255.0
x_test = x_test.reshape(x_test.shape[0], -1) / 255.0
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

Первая архитектура

In [22]:
model = Sequential()
model.add(Dense(10, input_dim=784, activation='relu'))
model.add(Dense(10, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam',
metrics=['accuracy'])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Обучение

In [23]:
model.fit(x_train, y_train, epochs=10, validation_split=0.1)

Epoch 1/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.6539 - loss: 0.9939 - val_accuracy: 0.8330 - val_loss: 0.4896
Epoch 2/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8351 - loss: 0.4832 - val_accuracy: 0.8430 - val_loss: 0.4471
Epoch 3/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8446 - loss: 0.4485 - val_accuracy: 0.8475 - val_loss: 0.4384
Epoch 4/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8504 - loss: 0.4295 - val_accuracy: 0.8393 - val_loss: 0.4583
Epoch 5/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8533 - loss: 0.4143 - val_accuracy: 0.8488 - val_loss: 0.4381
Epoch 6/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8563 - loss: 0.4092 - val_accuracy: 0.8353 - val_loss: 0.4768
Epoch 7/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8592 - loss: 0.4001 - val_accuracy: 0.8602 - val_loss: 0.4097
Epoch 8/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8604 - loss: 0.3999 - 

 Результат тестовых данных

In [24]:
test_acc = model.evaluate(x_test, y_test)
print(test_acc)


313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8501 - loss: 0.4259
[0.4375399947166443, 0.8442000150680542]


Вторая архитектура

In [25]:
model2 = Sequential()
model2.add(Dense( 50, input_dim=784, activation='relu'))
model2.add(Dense(10, activation='softmax'))
model2.compile(loss='categorical_crossentropy', optimizer='adam',
metrics=['accuracy'])
model2.fit(x_train, y_train, epochs=10, validation_split=0.1)

Epoch 1/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.7579 - loss: 0.7024 - val_accuracy: 0.8430 - val_loss: 0.4477
Epoch 2/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8552 - loss: 0.4079 - val_accuracy: 0.8558 - val_loss: 0.3915
Epoch 3/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8651 - loss: 0.3727 - val_accuracy: 0.8692 - val_loss: 0.3745
Epoch 4/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.8732 - loss: 0.3503 - val_accuracy: 0.8625 - val_loss: 0.3824
Epoch 5/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8816 - loss: 0.3243 - val_accuracy: 0.8725 - val_loss: 0.3404
Epoch 6/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8884 - loss: 0.3068 - val_accuracy: 0.8708 - val_loss: 0.3601
Epoch 7/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8902 - loss: 0.3016 - val_accuracy: 0.8800 - val_loss: 0.3408
Epoch 8/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8953 - loss: 0.2846 - 

Результат тестовых данных второй архитектуры

In [26]:
test_acc = model2.evaluate(x_test, y_test)
print(test_acc)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8762 - loss: 0.3496
[0.3563210070133209, 0.8748999834060669]


Архитектура три

In [27]:
model3 = Sequential()
model3.add(Dense(50, input_dim=784, activation='relu'))
model3.add(Dense(50, activation='relu'))
model3.add(Dense(10, activation='softmax'))
model3.compile(loss='categorical_crossentropy', optimizer='adam',
metrics=['accuracy'])
model3.fit(x_train, y_train, epochs=10, validation_split=0.1)

Epoch 1/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.7592 - loss: 0.7037 - val_accuracy: 0.8422 - val_loss: 0.4269
Epoch 2/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8575 - loss: 0.3974 - val_accuracy: 0.8647 - val_loss: 0.3691
Epoch 3/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8707 - loss: 0.3540 - val_accuracy: 0.8660 - val_loss: 0.3663
Epoch 4/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8786 - loss: 0.3267 - val_accuracy: 0.8697 - val_loss: 0.3598
Epoch 5/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.8856 - loss: 0.3095 - val_accuracy: 0.8722 - val_loss: 0.3492
Epoch 6/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.8927 - loss: 0.2945 - val_accuracy: 0.8778 - val_loss: 0.3404
Epoch 7/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.8933 - loss: 0.2866 - val_accuracy: 0.8700 - val_loss: 0.3568
Epoch 8/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8982 - loss: 0.2735

Результат тестовых даных

In [28]:
test_acc = model3.evaluate(x_test, y_test)
print(test_acc)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8712 - loss: 0.3710
[0.37615859508514404, 0.8698999881744385]


Сверточная нейроная сеть

In [29]:
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten
import numpy as np
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()
x_train = x_train[:,:,:,np.newaxis] / 255.0
x_test = x_test[:,:,:,np.newaxis] / 255.0
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

Архитектура четвертая

In [30]:
model4 = Sequential()
model4.add(Conv2D(filters=64, kernel_size=2, padding='same',
activation='relu', input_shape=(28,28, 1)))
model4.add(MaxPooling2D(pool_size=2))
model4.add(Flatten())
model4.add(Dense(10, activation='softmax'))
model4.compile(loss='categorical_crossentropy', optimizer='adam',
metrics=['accuracy'])
model4.fit(x_train, y_train, epochs=10, validation_split=0.1)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 46s 26ms/step - accuracy: 0.8014 - loss: 0.5779 - val_accuracy: 0.8853 - val_loss: 0.3402
Epoch 2/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 44s 26ms/step - accuracy: 0.8934 - loss: 0.3034 - val_accuracy: 0.8938 - val_loss: 0.3045
Epoch 3/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 83s 26ms/step - accuracy: 0.9010 - loss: 0.2825 - val_accuracy: 0.8978 - val_loss: 0.2933
Epoch 4/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 78s 24ms/step - accuracy: 0.9103 - loss: 0.2526 - val_accuracy: 0.9033 - val_loss: 0.2748
Epoch 5/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 42s 25ms/step - accuracy: 0.9171 - loss: 0.2333 - val_accuracy: 0.9027 - val_loss: 0.2798
Epoch 6/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 82s 25ms/step - accuracy: 0.9199 - loss: 0.2247 - val_accuracy: 0.9025 - val_loss: 0.2800
Epoch 7/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 82s 25ms/step - accuracy: 0.9271 - loss: 0.2072 - val_accuracy: 0.9050 - val_loss: 0.2727
Epoch 8/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 42s 25ms/step - accuracy: 0.9307 -

Результат тестовых данных

In [31]:
test_acc = model4.evaluate(x_test, y_test)
print(test_acc)

313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.9007 - loss: 0.2907
[0.2921716570854187, 0.8980000019073486]


Индивидуальное задание номер 9

In [32]:
import numpy as np
import random

Входные данные
Архитектура 2-4-2
Скорость обучения 0,35
Входные вектор X={0.1 -0.1}
Матрицы синапсов 1 и 2 слоя Начальные значения весов взять произвольным образом из интервала [-0.3, 0.3]
Эталонный вход Y= {0.5; -0.5}

In [36]:
# Функция активации: логистический сигмоид
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Производная функции активации: сигмоид
def sigmoid_derivative(x):
    return x * (1 - x)

# Параметры нейронной сети
input_size = 2  # Количество входов
hidden_size = 4  # Количество нейронов в скрытом слое
output_size = 2  # Количество выходов
learning_rate = 0.35

# Инициализация весов случайными значениями в диапазоне от -0.3 до 0.3
np.random.seed(42)  # Для воспроизводимости
weights_input_hidden = np.random.uniform(-0.3, 0.3, (input_size, hidden_size))
weights_hidden_output = np.random.uniform(-0.3, 0.3, (hidden_size, output_size))

# Входной вектор
X = np.array([[0.1], [-0.1]])
# Эталонный выход
Y = np.array([[0.5], [-0.5]])

Обучение сети

In [37]:
for epoch in range(10000):  # Количество эпох

    hidden_input = np.dot(X.T, weights_input_hidden)  # Входы в скрытый слой
    hidden_output = sigmoid(hidden_input)  # Выходы скрытого слоя

    output_input = np.dot(hidden_output, weights_hidden_output)  # Входы в выходной слой
    output_output = sigmoid(output_input)  # Выходы сети

Расчет ошибки и обнавление весов

In [41]:
error = Y - output_output  # Ошибка на выходе
if epoch % 1000 == 0:  # Печать ошибки каждые 1000 эпох
        print(f"Epoch {epoch}, Error: {np.mean(np.abs(error))}")

    # Обратное распространение ошибки
d_output = error * sigmoid_derivative(output_output)  # Градиент для выходного слоя
error_hidden = d_output.dot(weights_hidden_output.T)  # Ошибка в скрытом слое
d_hidden = error_hidden * sigmoid_derivative(hidden_output)  # Градиент для скрытого слоя


Итог

In [42]:
print("Весовая матрица между входным слоем и скрытым слоем:")
print(weights_input_hidden)

print("Весовая матрица между скрытым слоем и выходным слоем:")
print(weights_hidden_output)

print("Финальный выход нейросети:")
print(output_output)

Весовая матрица между входным слоем и скрытым слоем:
[[-0.07527593  0.27042858  0.13919637  0.05919509]
 [-0.20638882 -0.20640329 -0.26514983  0.21970569]]
Весовая матрица между скрытым слоем и выходным слоем:
[[ 0.06066901  0.12484355]
 [-0.2876493   0.28194591]
 [ 0.19946558 -0.17259653]
 [-0.19090502 -0.18995729]]
Финальный выход нейросети:
[[0.47261312 0.50622597]]
